// <auto-generated />
using System;
using CarePartnersPortal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarePartnersPortal.Migrations
{
    [DbContext(typeof(DBContextProcura))]
    [Migration("20201105202241_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarePartnersPortal.ProcuraFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DEF_SUBJECT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("File_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("File_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File_Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("File_Size")
                        .HasColumnType("int");

                    b.Property<string>("File_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_DB_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ZIP_File_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ZIP_File_Size")
                        .HasColumnType("int");

                    b.Property<decimal>("client_number")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("ID");

                    b.ToTable("ProcuraFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
